### ISSUE TITLE
Mupen Utilities Exception

### ISSUE THREAD

**Issue by LukeSaward1** [Aurumaker72/MupenUtilities#5] opened 2021-06-26 08:00 UTC
### MupenUtilities crash log

[exception.log](https://github.com/Aurumaker72/MupenUtilities/files/6719798/exception.log)

**Comment by Aurumaker72** [comment] 2021-06-26 10:30
I'll look into this asap

**Comment by Aurumaker72** [comment] 2021-06-26 10:41
Issue resolved in commit 2f2d4cc0223ebaff2a0bfe0226e91d47a24f9fcb
The cause was a race condition between TAS Studio and M64 Loading thread

**Closed by Aurumaker72** 2021-06-26 10:41 UTC
Labels: bug
